// <auto-generated />
namespace medical_appointment_scheduling_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dbthucuc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbthucuc));
        
        string IMigrationMetadata.Id
        {
            get { return "202311260946285_dbthucuc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
