// <auto-generated />
namespace medical_appointment_scheduling_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dbthucus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbthucus));
        
        string IMigrationMetadata.Id
        {
            get { return "202312010834541_dbthucus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
